-- ============================================================================
-- Migration 001 — Continuous Improvement Pipeline
-- ============================================================================
-- Adds tables for storing critiques generated by the Claude judge over
-- poorly-rated conversations (<= 3 stars), the failure-mode taxonomy used
-- to keep critique labels consistent enough to aggregate, and a log of
-- which suggested fixes were applied vs dismissed.
--
-- Idempotent: safe to run multiple times.
-- Run with:  psql -d ai_support -f scripts/migration001.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Failure mode taxonomy
-- ----------------------------------------------------------------------------
-- A fixed enum of failure codes the judge must pick from. Free-form labels
-- would defeat aggregation on the dashboard.
CREATE TABLE IF NOT EXISTS failure_mode_taxonomy (
    code        TEXT PRIMARY KEY,
    label       TEXT NOT NULL,
    description TEXT
);

INSERT INTO failure_mode_taxonomy (code, label, description) VALUES
    ('WRONG_INTENT',              'Wrong intent',                 'Intent agent misclassified the user request.'),
    ('LOW_CONFIDENCE_NOT_ESCALATED', 'Low confidence not escalated', 'Confidence was borderline but the conversation was not escalated.'),
    ('POLICY_IGNORED',            'Policy ignored',               'Agent gave an answer that contradicts an authoritative policy doc.'),
    ('POLICY_MISQUOTED',          'Policy misquoted',             'Agent invented or distorted policy details.'),
    ('MISSING_CONTEXT',           'Missing context',              'Agent did not use available customer or order context.'),
    ('WRONG_AGENT_ROUTED',        'Wrong agent routed',           'Coordinator routed to the wrong specialist agent.'),
    ('SENTIMENT_MISSED',          'Sentiment missed',             'Negative sentiment was not detected or not acted upon.'),
    ('INCOMPLETE_ANSWER',         'Incomplete answer',            'Agent stopped before fully resolving the request.'),
    ('HALLUCINATED_ACTION',       'Hallucinated action',          'Agent claimed to perform an action it did not perform.'),
    ('TONE_INAPPROPRIATE',        'Tone inappropriate',           'Agent tone was wrong for the situation (curt, robotic, etc.).'),
    ('LANGUAGE_CONFUSION',        'Language confusion',           'Mismatch between user language and agent response.'),
    ('INFINITE_LOOP',             'Infinite loop',                'Agents bounced without making progress toward resolution.'),
    ('ESCALATION_FAILED',         'Escalation failed',            'Conversation was escalated but never reached a human.'),
    ('SLOW_RESPONSE',             'Slow response',                'Excessive latency between user turn and agent reply.'),
    ('OTHER',                     'Other',                        'Failure not covered by the existing taxonomy.')
ON CONFLICT (code) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Conversation critiques
-- ----------------------------------------------------------------------------
-- One row per critique run. A conversation can have multiple critiques if
-- re-run with a newer prompt version.
CREATE TABLE IF NOT EXISTS conversation_critiques (
    critique_id        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id    UUID NOT NULL REFERENCES completed_conversations(conversation_id) ON DELETE CASCADE,
    review_score       SMALLINT NOT NULL,
    prompt_version     TEXT NOT NULL,
    model              TEXT NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),

    -- structured judgment fields
    overall_summary    TEXT,
    severity           TEXT,
    root_cause_agent   TEXT,
    rating_seems_fair  BOOLEAN,
    failure_modes      JSONB,
    policy_violations  JSONB,
    suggested_fixes    JSONB,

    -- diagnostics
    raw_response       JSONB,
    error              TEXT
);

CREATE INDEX IF NOT EXISTS idx_critiques_conv      ON conversation_critiques(conversation_id);
CREATE INDEX IF NOT EXISTS idx_critiques_agent     ON conversation_critiques(root_cause_agent);
CREATE INDEX IF NOT EXISTS idx_critiques_severity  ON conversation_critiques(severity);
CREATE INDEX IF NOT EXISTS idx_critiques_created   ON conversation_critiques(created_at DESC);

-- ----------------------------------------------------------------------------
-- Fix application log
-- ----------------------------------------------------------------------------
-- Tracks operator decisions on each suggested fix in a critique:
-- whether it was applied to the system, dismissed, or left open.
CREATE TABLE IF NOT EXISTS fix_application_log (
    log_id        SERIAL PRIMARY KEY,
    critique_id   UUID NOT NULL REFERENCES conversation_critiques(critique_id) ON DELETE CASCADE,
    fix_index     INT NOT NULL,
    status        TEXT NOT NULL,
    note          TEXT,
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (critique_id, fix_index)
);

CREATE INDEX IF NOT EXISTS idx_fix_log_critique ON fix_application_log(critique_id);
CREATE INDEX IF NOT EXISTS idx_fix_log_status   ON fix_application_log(status);
